In [31]:
# https://github.com/AndersonJo/hanhwa_202609_data_engineering/
import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7]
arr = np.array(my_list)
print(arr)
sub_arr = arr[1:3] # .copy()
print(sub_arr)
sub_arr[0] = 999
print(sub_arr)
print(arr)

[1 2 3 4 5 6 7]
[2 3]
[999   3]
[  1 999   3   4   5   6   7]


# Broadcasting 

$ \frac{y}{x} = x^{123} + y $

In [34]:
x = np.arange(0, 9).reshape(3, 3)
x[x >= 4] = -1
x

array([[ 0,  1,  2],
       [ 3, -1, -1],
       [-1, -1, -1]])

In [39]:
a = np.arange(1, 10).reshape(3, 3)
b = np.array([10, 20, 30])
print(a)
a + b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [22]:
from helper import load_ages, describe, load_titanic_matrix, COLS
ages = load_ages()
describe(ages)
m = load_titanic_matrix()
print(COLS)
print(ages.sum())
print(ages.mean())
print(ages.min(), ages.max(), ages.std())

shape : (714,)
ndim  : 1
dtype : float64
first : [22. 38. 26. 35. 35.]
['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
21205.17
29.69911764705882
0.42 80.0 14.516321150817316


In [27]:
fares = np.array([100, 200, 400, 500, 20])
print(fares ** 2)
print(np.log1p(fares))

[ 10000  40000 160000 250000    400]
[4.61512052 5.30330491 5.99396143 6.2166061  3.04452244]
